#page title
page_title                                : POSITIVE INFINITY                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/dev?id=5604259480781805867                                          # Enter Google Play Store URL.
presskit_download_link                    :   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : POSITIVE INFINITY                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Android Apps                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Search and find ATMs, toilets, gas stations, playgrounds and much more.<br>Nearby and anywhere in the world.

# Information About Yourself
your_name                                 : POSITIVE INFINITY                                
your_link                                 : https://positive-infinity.software/ 
your_city                                 : Bielefeld                                
email_address                             : positive.infinity.development@gmail.com
facebook_username                         : positive.infinity.apps                                          
whatsapp_link                             : https://wa.me/4952144815307
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : The right app for each use case
    description                           : Find ATMs, toilets, gas stations, supermarkets, playgrounds and much more, each with its own dedicated app.
    fontawesome_icon_name                 : magic
    
  - title                                 : Nearby and anywhere in the world
    description                           : Search next to your location or anywhere in the world by specifying an address, POI or a point on the map.
    fontawesome_icon_name                 : map-marker

  - title                                 : List, Map & Details
    description                           : Quickly overview locations by using the list or map view. Focus on one item in the details view.
    fontawesome_icon_name                 : map

  - title                                 : Community driven
    description                           : Hundreds of updates are worked in into the databases on each and every day.
    fontawesome_icon_name                 : sync

  - title                                 : Free
    description                           : All the basic functionality is completely free. Go PRO for additional features and to support further development.
    fontawesome_icon_name                 : star
  
  - title                                 : Dark Mode
    description                           : Configure your theming as you like. Use the device setting or force dark or light mode.
    fontawesome_icon_name                 : adjust

  - title                                 : Navigation
    description                           : Use Google Maps or various third-party navigation software to easiliy navigate to an item.
    fontawesome_icon_name                 : directions

  - title                                 : Support for tablets and watches
    description                           : The app works equally well on phones as on tablets. The latest version now also supports watches running Wear OS.
    fontawesome_icon_name                 : tablet

  - title                                 : Accessibility
    description                           : Accessibility information is available for more and more apps.
    fontawesome_icon_name                 : wheelchair


# App List                                Edit, add or remove apps to be presented.
apps                                      :
  
  - title                                 : Around Me
    description                           : Find everything around you.
    id                                    : aroundme
    
  - title                                 : ATM Locator
    description                           : Find cash machines anywhere in the world.
    id                                    : atmlocator
    
  - title                                 : Attraction Locator
    description                           : Sight seeing via app.
    id                                    : attractionlocator

  - title                                 : Bakery Locator
    description                           : Bakeries nearby and only a click away.
    id                                    : bakerylocator
    
  - title                                 : Camping Locator
    description                           : Find camping places and caravan spaces wherever you are.
    id                                    : campinglocator

  - title                                 : Cash Group Locator
    description                           : Locate ATMs of the german Cash Group banking association.
    id                                    : cashgrouplocator
    
  - title                                 : Cash Pool Locator
    description                           : Locate ATMs of the german Cash Pool banking association.
    id                                    : cashpoollocator
    
  - title                                 : Church Locator
    description                           : Find local churches.
    id                                    : churchlocator
    
  - title                                 : Fast Food Locator
    description                           : Find fast food restaurants and grills for a quick snack.
    id                                    : fflocator
    
  - title                                 : Gas Station & Fuel Locator
    description                           : Gas stations always in sight with this app.
    id                                    : fuellocator
    
  - title                                 : History Locator
    description                           : Explore historic places nearby and learn something new every day.
    id                                    : historylocator
    
  - title                                 : Hotel Locator
    description                           : Hotels and guesthouses wherever you are.
    id                                    : hotellocator
    
  - title                                 : Parking Locator
    description                           : Find parking spaces and garages.
    id                                    : parkinglocator
    
  - title                                 : Pharmacy Locator
    description                           : Find pharmacies, drugstores and chemists with this app.
    id                                    : pharmacylocator
        
  - title                                 : Playground Locator
    description                           : Explore unknown playgrounds around you.
    id                                    : playgroundlocator
    
  - title                                 : Restaurant Locator
    description                           : Find restaurants nearby and anywhere in the world.
    id                                    : restaurantlocator
    
  - title                                 : Supermarket Locator
    description                           : Find supermarkets and grocery stores anyplace.
    id                                    : shoplocator
    
  - title                                 : Toilet Locator
    description                           : Find public restrooms. Including accessibility information.
    id                                    : toiletlocator


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#222222"

link_color                                : "#d2241e"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#bbbbbb"

feature_icons_foreground_color            : "#d2241e"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true

# Markdown rendering
markdown: kramdown